[[relayer_evm]]
name = "Ethereum"
call_contract = "0xe432150cce91c13a887f7D836923d5597adD8E31"
rpc_addr = "https://mainnet.infura.io/ws/v3/c60b0bb42f8a4c6481ecd229eddaca27"
ws_addr = "wss://mainnet.infura.io/ws/v3/c60b0bb42f8a4c6481ecd229eddaca27"
start_with_bridge = false

[[relayer_evm]]
name = "Goerli"
call_contract = "0x10A69f82Ed4E8E058b399f8aA5216Aa2602C7a52"
rpc_addr = "https://eth-goerli.g.alchemy.com/v2/DpCscOiv_evEPscGYARI3cOVeJ59CRo8"
ws_addr = "wss://eth-goerli.g.alchemy.com/v2/DpCscOiv_evEPscGYARI3cOVeJ59CRo8"
start_with_bridge = true

[[relayer_evm]]
name = "Avalanche"
call_contract = "0xC249632c2D40b9001FE907806902f63038B737Ab"
#rpc_addr = "http://local_chains:8500/1"
#ws_addr = "ws://local_chains:8500/1"
#ws_addr = "wss://mainnet.infura.io/ws/v3/c60b0bb42f8a4c6481ecd229eddaca27"
start_with_bridge = true