version: "3.9"

services:
  validator-builder:
    build:
      context: ../..
      dockerfile: ./docker/sui-test-validator/builder.Dockerfile
      args:
        # update with git sha of whichever branch you're building on.
        GIT_REVISION: db24658bc9
        BUILD_DATE: today

    environment:
      - LD_PRELOAD
      - RUST_JSON_LOG="true"
      - RUST_LOG="info"
      # don't use debug, it generates volumes of data.
    image: sui-validator-builder
    container_name: sui-validator-builder
    command: sleep infinity
    restart: unless-stopped
    working_dir: /sui
    # populate your local ./fullnode/config/ directory with fullnode.yaml and genesis.blob for the network you want to use.
    volumes:
      - ../..:/sui
      - ./validator/build.sh:/sui/build.sh
      - ./validator/debug:/sui/target/debug:rw
      - ./validator/release:/sui/target/release:rw

  validator-runner:
    build:
      context: ../..
      dockerfile: ./docker/sui-test-validator/runner.Dockerfile
      args:
        # update with git sha of whichever branch you're building on.
        GIT_REVISION: db24658bc9
        BUILD_DATE: today
    environment:
      - LD_PRELOAD
      - RUST_JSON_LOG="true"
      - RUST_LOG="info"
      # don't use debug, it generates volumes of data.
    image: sui-validator-runner
    container_name: sui-validator-runner
    #command: /opt/sui/entry.sh
    command: sleep infinity
    restart: unless-stopped
    working_dir: /opt/sui
    # populate your local ./fullnode/config/ directory with fullnode.yaml and genesis.blob for the network you want to use.
    volumes:
      - ./validator:/opt/sui
      - ./validator/debug/sui-test-validator:/usr/local/bin/sui-test-validator
      - ./validator/debug/sui:/usr/local/bin/sui
      - ./validator/nginx.conf:/etc/nginx/sites-available/default
    ports:
      - 9000:8000
      - 9184:8184
      - 9123:8123
      - 9124:8124
      - target: 8084
        published: 8084
        protocol: udp      

